"use client";

// "About VedaSaarathi" - one small bilingual page reached from Home (Back
// returns to Home). Plain text only: no tracking, no forms, nothing is sent
// anywhere from this page. The feedback route is a plain mailto: link; the
// visitor sends the message themselves from their own email app.

import { Mail } from "lucide-react";
import { useEffect, useState } from "react";

import { clearAllStoredData } from "@/lib/storage/clear-all";

export const FEEDBACK_EMAIL = "contact.vedasarathi@gmail.com";
export const FEEDBACK_MAILTO = `mailto:${FEEDBACK_EMAIL}`;
export const COPYRIGHT_LINE = "© 2026 ASCOR LABS. All rights reserved.";
/** Served from public/ and precached for offline use. Generated by
 * scripts/generate-third-party-notices.mjs from the installed packages. */
export const THIRD_PARTY_NOTICES_URL = "/THIRD_PARTY_NOTICES.txt";

/** Confirmed "With gratitude" entries. Add an entry ONLY with details and
 * consent supplied by the project owner: preferred name and title, and the
 * specific contribution. While this list is empty the section is not
 * rendered at all - never show a placeholder, an endorsement, or a
 * qualification that was not supplied. "Reviewed by" wording is only for the
 * particular content that person actually reviewed. */
export interface PriestAcknowledgement {
  en: string;
  te: string;
}
export const PRIEST_ACKNOWLEDGEMENTS: readonly PriestAcknowledgement[] = [];

const T = {
  EN: {
    title: "About VedaSaarathi",
    whyH: "Why VedaSaarathi exists",
    why: [
      "Living away from home can make simple questions difficult: What is today’s tithi? When is the next festival where I live? How can my family prepare for a puja?",
      "VedaSaarathi brings these details together in simple English and Telugu, using your selected location.",
    ],
    whatH: "What you can do",
    what: [
      "See today’s Panchangam and traditional daily timings.",
      "Find supported festivals and monthly observances in your local calendar.",
      "Follow the puja guides currently available.",
    ],
    whereH: "Why location matters",
    where:
      "Sunrise and sunset happen at different times around the world. A festival’s date or observance time can sometimes differ between India and where you live.",
    traditionH: "Our tradition and guidance",
    tradition: [
      "VedaSaarathi is rooted in Hindu traditions. Practices can differ between families, regions and traditions. We use published Panchangam references and traditional sources, and explain important conventions in the relevant calculation details.",
      "This app supports learning and practice. For questions specific to your family or a ceremony, seek guidance from your priest or family elders. Content awaiting priest review is not presented as priest-approved.",
    ],
    coverageH: "First-version coverage",
    coverage:
      "This first version includes a growing selection of festivals and puja guides. It does not yet cover every festival or tradition.",
    aiH: "AI and review",
    ai: [
      "AI tools have helped us develop parts of VedaSaarathi and prepare some content. The daily Panchangam is calculated on your device by an astronomical calculation program, not by an AI chatbot. Puja audio uses a computer-generated voice, including the mantra pronunciation guides, which a priest has not yet reviewed.",
      "AI-assisted content can contain errors in wording, translation or pronunciation, and calculations and software can also contain mistakes.",
      "Not all religious content has been reviewed by a priest. We are continuing to review and improve it.",
    ],
    thanksH: "With gratitude",
    feedbackH: "Found something that does not look right?",
    feedback:
      "Please let us know if you notice an incorrect date, timing, translation, pronunciation or religious instruction. Your feedback helps us improve VedaSaarathi with care and respect.",
    feedbackHow: `Found a mistake or have a suggestion? Please email us at ${FEEDBACK_EMAIL}. For a date or timing issue, include the city and date selected in the app. Please avoid sharing private family details.`,
    emailUs: "Email us",
    emailNote:
      "This link opens your email app. You need to send the message yourself. VedaSaarathi does not send anything for you.",
    projectH: "About the project",
    project: [
      "VedaSaarathi is a project by ASCOR LABS.",
      "VedaSaarathi’s guidance is free to use.",
      "Traditional texts and third-party sources belong to their respective authors and owners.",
    ],
    dataH: "Data on this device",
    dataIntro:
      "Your saved location, people and their details, puja progress, saved corrections, calendar cache and preferences are stored only in this browser, on this device.",
    clearButton: "Clear saved data on this device",
    clearConfirm:
      "Clear all VedaSaarathi data saved on this device? This removes your saved location, people and their details, puja progress, saved corrections, calendar cache and preferences. It does not remove a downloaded offline copy of the puja audio — remove that separately from Pujas → Offline → “Remove downloaded copy”.",
    buildLabel: "App build",
    buildUnknown: "Build information is not available.",
    noticesH: "Third-party notices",
    noticesIntro:
      "VedaSaarathi’s own code and content are by ASCOR LABS. It also includes open-source software written by others, which stays with its authors under its own licence. Their copyright and licence notices are listed here.",
    noticesShow: "Show third-party notices",
    noticesLoading: "Loading…",
    noticesError: "Could not load the notices. Please check your connection and try again.",
    noticesRetry: "Try again",
  },
  TE: {
    title: "వేదసారథి గురించి",
    whyH: "వేదసారథి ఎందుకు?",
    why: [
      "ఇంటికి దూరంగా ఉన్నప్పుడు సాధారణ ప్రశ్నలు కూడా కష్టంగా అనిపించవచ్చు: ఈ రోజు తిథి ఏమిటి? నేను ఉన్న చోట తదుపరి పండుగ ఎప్పుడు? మా కుటుంబం పూజకు ఎలా సిద్ధం కావాలి?",
      "వేదసారథి ఈ వివరాలన్నింటినీ, మీరు ఎంచుకున్న ప్రదేశం ఆధారంగా, సరళమైన ఇంగ్లీష్, తెలుగులో ఒకే చోట అందిస్తుంది.",
    ],
    whatH: "మీరు ఏమి చేయవచ్చు",
    what: [
      "నేటి పంచాంగాన్ని, సంప్రదాయ రోజువారీ సమయాలను చూడండి.",
      "మీ స్థానిక క్యాలెండర్‌లో మేము చేర్చిన పండుగలను, నెలవారీ వ్రతాలను తెలుసుకోండి.",
      "ప్రస్తుతం అందుబాటులో ఉన్న పూజా మార్గదర్శకాలను అనుసరించండి.",
    ],
    whereH: "ప్రదేశం ఎందుకు ముఖ్యం",
    where:
      "సూర్యోదయం, సూర్యాస్తమయం ప్రపంచంలో ఒక్కోచోట ఒక్కో సమయానికి అవుతాయి. అందువల్ల పండుగ తేదీ లేదా ఆచరణ సమయం భారతదేశంలో, మీరు నివసించే చోట కొన్నిసార్లు భిన్నంగా ఉండవచ్చు.",
    traditionH: "మా సంప్రదాయం, మార్గదర్శకం",
    tradition: [
      "వేదసారథి హిందూ సంప్రదాయాల ఆధారంగా రూపొందింది. ఆచరణలు కుటుంబాన్ని, ప్రాంతాన్ని, సంప్రదాయాన్ని బట్టి మారవచ్చు. మేము ప్రచురితమైన పంచాంగ ఆధారాలను, సంప్రదాయ మూలాలను ఉపయోగిస్తాము; ముఖ్యమైన పద్ధతులను సంబంధిత లెక్కల వివరాల్లో వివరిస్తాము.",
      "ఈ యాప్ నేర్చుకోవడానికి, ఆచరణకు తోడ్పడుతుంది. మీ కుటుంబానికి లేదా ఒక కార్యక్రమానికి సంబంధించిన సందేహాలకు మీ పురోహితులను లేదా ఇంటి పెద్దలను సంప్రదించండి. పురోహితుల సమీక్ష ఇంకా జరగని విషయాన్ని పురోహితులు ఆమోదించినదిగా చూపము.",
    ],
    coverageH: "మొదటి వెర్షన్‌లో ఏముంది",
    coverage:
      "ఈ మొదటి వెర్షన్‌లో పండుగలు, పూజా మార్గదర్శకాల ఎంపిక ఉంది; అది క్రమంగా పెరుగుతుంది. ఇది ఇంకా ప్రతి పండుగను, ప్రతి సంప్రదాయాన్ని కవర్ చేయదు.",
    aiH: "AI, సమీక్ష",
    ai: [
      "వేదసారథిలోని కొన్ని భాగాల అభివృద్ధికి, కొంత సమాచారం సిద్ధం చేయడానికి AI సాధనాలు మాకు సహాయపడ్డాయి. రోజువారీ పంచాంగాన్ని ఖగోళ గణన ప్రోగ్రామ్ మీ పరికరంలోనే లెక్కిస్తుంది; అది AI చాట్‌బాట్ కాదు. పూజా ఆడియోలో కంప్యూటర్ రూపొందించిన స్వరం వాడాము; మంత్రాల ఉచ్చారణ ఆడియో కూడా అందులో ఉంది, దానిని పురోహితులు ఇంకా సమీక్షించలేదు.",
      "AI సహాయంతో రూపొందిన సమాచారంలో పదాలు, అనువాదం, ఉచ్చారణలో తప్పులు ఉండవచ్చు; లెక్కల్లో, సాఫ్ట్‌వేర్‌లో కూడా పొరపాట్లు ఉండవచ్చు.",
      "మత సంబంధిత విషయమంతా పురోహితులు సమీక్షించలేదు. సమీక్షను, మెరుగుదలను కొనసాగిస్తున్నాము.",
    ],
    thanksH: "కృతజ్ఞతలు",
    feedbackH: "ఏదైనా సరిగా లేదనిపించిందా?",
    feedback:
      "తప్పు తేదీ, సమయం, అనువాదం, ఉచ్చారణ లేదా మతపరమైన సూచన కనిపిస్తే దయచేసి మాకు తెలియజేయండి. మీ అభిప్రాయం వేదసారథిని శ్రద్ధతో, గౌరవంతో మెరుగుపరచడానికి సహాయపడుతుంది.",
    feedbackHow: `పొరపాటు కనిపించినా, సూచన ఉన్నా ${FEEDBACK_EMAIL} కు ఈమెయిల్ చేయండి. తేదీ లేదా సమయం గురించి అయితే యాప్‌లో ఎంచుకున్న నగరం, తేదీ కూడా రాయండి. దయచేసి కుటుంబానికి సంబంధించిన వ్యక్తిగత వివరాలు పంపకండి.`,
    emailUs: "మాకు ఈమెయిల్ చేయండి",
    emailNote:
      "ఈ లింక్ మీ ఈమెయిల్ యాప్‌ను తెరుస్తుంది. సందేశాన్ని మీరే పంపాలి. వేదసారథి మీ తరపున ఏదీ పంపదు.",
    projectH: "ప్రాజెక్ట్ గురించి",
    project: [
      "వేదసారథి ASCOR LABS ప్రాజెక్ట్.",
      "వేదసారథి మార్గదర్శకం ఉపయోగించడానికి ఉచితం.",
      "సంప్రదాయ గ్రంథాలు, ఇతర మూలాలు వాటి రచయితలకు, యజమానులకు చెందినవి.",
    ],
    dataH: "ఈ పరికరంలో డేటా",
    dataIntro:
      "మీ సేవ్ చేసిన ప్రదేశం, వ్యక్తులు, వారి వివరాలు, పూజ పురోగతి, సేవ్ చేసిన సవరణలు, క్యాలెండర్ కాష్, ప్రాధాన్యతలు ఈ బ్రౌజర్‌లో, ఈ పరికరంలో మాత్రమే నిల్వ ఉంటాయి.",
    clearButton: "ఈ పరికరంలో సేవ్ చేసిన డేటాను తొలగించండి",
    clearConfirm:
      "ఈ పరికరంలో సేవ్ చేసిన వేదసారథి డేటా మొత్తాన్ని తొలగించాలా? ఇది మీ సేవ్ చేసిన ప్రదేశం, వ్యక్తులు, వారి వివరాలు, పూజ పురోగతి, సేవ్ చేసిన సవరణలు, క్యాలెండర్ కాష్, ప్రాధాన్యతలను తొలగిస్తుంది. ఇది ఆఫ్‌లైన్ కోసం డౌన్‌లోడ్ చేసిన పూజ ఆడియోను తొలగించదు — దానిని పూజలు → ఆఫ్‌లైన్ → “డౌన్‌లోడ్ చేసిన కాపీని తీసివేయండి” నుండి వేరుగా తొలగించండి.",
    buildLabel: "యాప్ బిల్డ్",
    buildUnknown: "బిల్డ్ సమాచారం అందుబాటులో లేదు.",
    noticesH: "మూడవ పక్ష నోటీసులు",
    noticesIntro:
      "వేదసారథి సొంత కోడ్, కంటెంట్ ASCOR LABS వి. ఇందులో ఇతరులు రాసిన ఓపెన్-సోర్స్ సాఫ్ట్‌వేర్ కూడా ఉంది; అది వాటి రచయితలకే చెందుతుంది, వాటి సొంత లైసెన్స్ కింద ఉంటుంది. వారి కాపీరైట్, లైసెన్స్ నోటీసులు ఇక్కడ ఉన్నాయి.",
    noticesShow: "మూడవ పక్ష నోటీసులు చూపించండి",
    noticesLoading: "లోడ్ అవుతోంది…",
    noticesError: "నోటీసులను లోడ్ చేయలేకపోయాం. మీ కనెక్షన్ చూసి మళ్ళీ ప్రయత్నించండి.",
    noticesRetry: "మళ్ళీ ప్రయత్నించండి",
  },
} as const;

type NoticesState =
  | { status: "idle" }
  | { status: "loading" }
  | { status: "ready"; text: string }
  | { status: "error" };

/** The notices are loaded on demand with a normal same-origin request, so the
 * offline download's cache answers it with no network. (A new-tab navigation
 * to the file would be answered with the app shell while offline.) */
function ThirdPartyNotices({ te }: { te: boolean }) {
  const t = te ? T.TE : T.EN;
  const [state, setState] = useState<NoticesState>({ status: "idle" });

  const load = async () => {
    setState({ status: "loading" });
    try {
      const res = await fetch(THIRD_PARTY_NOTICES_URL);
      if (!res.ok) throw new Error(String(res.status));
      setState({ status: "ready", text: await res.text() });
    } catch {
      setState({ status: "error" });
    }
  };

  return (
    <section className="about-notices">
      <h2>{t.noticesH}</h2>
      <p>{t.noticesIntro}</p>
      <details
        onToggle={(e) => {
          if (e.currentTarget.open && (state.status === "idle" || state.status === "error")) void load();
        }}
      >
        <summary>{t.noticesShow}</summary>
        {state.status === "loading" && <p role="status">{t.noticesLoading}</p>}
        {state.status === "error" && (
          <p role="alert">
            {t.noticesError}{" "}
            <button type="button" className="link-button" onClick={() => void load()}>{t.noticesRetry}</button>
          </p>
        )}
        {state.status === "ready" && (
          <pre className="about-notices-text" lang="en" tabIndex={0} aria-label={t.noticesH}>{state.text}</pre>
        )}
      </details>
    </section>
  );
}

interface BuildInfo {
  commitShort: string | null;
  builtAt: string;
  dirty: boolean;
}

/** Fetched once, same-origin, cached offline like the notices file. Shown
 * small and plain - just enough to tell one deployed build apart from
 * another when comparing notes or deciding what to roll back to. */
function BuildInfoLine({ te }: { te: boolean }) {
  const t = te ? T.TE : T.EN;
  const [info, setInfo] = useState<BuildInfo | null>(null);
  useEffect(() => {
    let alive = true;
    fetch("/build-info.json")
      .then((res) => (res.ok ? res.json() : null))
      .then((j: unknown) => {
        if (!alive || !j || typeof j !== "object") return;
        const o = j as Record<string, unknown>;
        if (typeof o.builtAt !== "string") return;
        setInfo({
          commitShort: typeof o.commitShort === "string" ? o.commitShort : null,
          builtAt: o.builtAt,
          dirty: o.dirty === true,
        });
      })
      .catch(() => {});
    return () => { alive = false; };
  }, []);
  if (!info) return <p className="about-build" lang="en">{t.buildUnknown}</p>;
  const date = info.builtAt.slice(0, 10);
  return (
    <p className="about-build" lang="en">
      {t.buildLabel}: {info.commitShort ?? "?"}{info.dirty ? "+" : ""} · {date}
    </p>
  );
}

/** "Clear saved data on this device" - confirmed with a native browser
 * confirm() dialog (the same established pattern as the completion screen's
 * "Delete all corrections", report-correction.tsx), which is also where the
 * exact list of what gets removed is stated. On confirm, every VedaSaarathi
 * key is cleared and the app reloads - the most direct, verifiable way to
 * "reset the visible app state immediately", since every screen's state is
 * freshly read from (now-empty) storage on that reload. */
function ClearDeviceData({ te }: { te: boolean }) {
  const t = te ? T.TE : T.EN;
  const clear = () => {
    if (typeof window === "undefined") return;
    if (typeof window.confirm === "function" && !window.confirm(t.clearConfirm)) return;
    clearAllStoredData();
    window.location.reload();
  };
  return (
    <section className="about-data">
      <h2>{t.dataH}</h2>
      <p>{t.dataIntro}</p>
      <button type="button" className="wide-secondary about-clear-data" onClick={clear}>
        {t.clearButton}
      </button>
    </section>
  );
}

export function AboutScreen({ language = "EN" }: { language?: "EN" | "TE" }) {
  const te = language === "TE";
  const t = te ? T.TE : T.EN;
  const lang = te ? "te" : undefined;

  return (
    <div className="flow-content about-page" lang={lang}>
      <h1>{t.title}</h1>

      <section>
        <h2>{t.whyH}</h2>
        {t.why.map((p) => <p key={p}>{p}</p>)}
      </section>

      <section>
        <h2>{t.whatH}</h2>
        <ul>{t.what.map((p) => <li key={p}>{p}</li>)}</ul>
      </section>

      <section>
        <h2>{t.whereH}</h2>
        <p>{t.where}</p>
      </section>

      <section>
        <h2>{t.traditionH}</h2>
        {t.tradition.map((p) => <p key={p}>{p}</p>)}
      </section>

      <section>
        <h2>{t.coverageH}</h2>
        <p>{t.coverage}</p>
      </section>

      <section>
        <h2>{t.aiH}</h2>
        {t.ai.map((p) => <p key={p}>{p}</p>)}
      </section>

      {PRIEST_ACKNOWLEDGEMENTS.length > 0 && (
        <section aria-label={t.thanksH}>
          <h2>{t.thanksH}</h2>
          {PRIEST_ACKNOWLEDGEMENTS.map((a) => (
            <p key={a.en}>{te ? a.te : a.en}</p>
          ))}
        </section>
      )}

      <section className="about-feedback">
        <h2>{t.feedbackH}</h2>
        <p>{t.feedback}</p>
        <p>{t.feedbackHow}</p>
        <a className="wide-primary" href={FEEDBACK_MAILTO}>
          <Mail size={18} /> {t.emailUs}
        </a>
        <p className="about-address" lang="en">{FEEDBACK_EMAIL}</p>
        <p className="info-note">{t.emailNote}</p>
      </section>

      <section>
        <h2>{t.projectH}</h2>
        {t.project.map((p) => <p key={p}>{p}</p>)}
      </section>

      <ThirdPartyNotices te={te} />

      <ClearDeviceData te={te} />

      <footer className="about-footer" lang="en">
        {COPYRIGHT_LINE}
        <BuildInfoLine te={te} />
      </footer>
    </div>
  );
}
